/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as classic from "./Classic";
export type { classic };
import type * as governance from "./Governance";
export type { governance };
