/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGovernance__factory } from "./IGovernance__factory";
export { ProposalStateChangeGovernance__factory } from "./ProposalStateChangeGovernance__factory";
