/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGovernance2__factory } from "./IGovernance2__factory";
export { ProposalStateChangeGovernance__factory } from "./ProposalStateChangeGovernance__factory";
