/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITornadoRouter } from "./ITornadoRouter";
export type { InstanceRegistry } from "./InstanceRegistry";
