/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GasCompensator } from "./GasCompensator";
export type { IGasCompensationVault } from "./IGasCompensationVault";
