/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testnetOracleSol from "./TestnetOracle.sol";
export type { testnetOracleSol };
export type { TestnetAdminProxy } from "./TestnetAdminProxy";
export type { TestnetFeeManager } from "./TestnetFeeManager";
export type { TestnetGovernanceProxy } from "./TestnetGovernanceProxy";
