/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestnetAdminProxy__factory } from "./TestnetAdminProxy__factory";
export { TestnetFeeManager__factory } from "./TestnetFeeManager__factory";
export { TestnetGovernanceProxy__factory } from "./TestnetGovernanceProxy__factory";
