/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IENSRegistry } from "./IENSRegistry";
export type { IENSResolver } from "./IENSResolver";
export type { IRelayerRegistry } from "./IRelayerRegistry";
export type { RelayerAggregator } from "./RelayerAggregator";
