/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iusdtSol from "./IUSDT.sol";
export type { iusdtSol };
export type { BadRecipient } from "./BadRecipient";
export type { ERC20Mock } from "./ERC20Mock";
export type { IDeployer } from "./IDeployer";
export type { MerkleTreeWithHistoryMock } from "./MerkleTreeWithHistoryMock";
