/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChainlinkOracle,
  IChainlinkOracleInterface,
} from "../../../../../contracts/Governance/Testnet/TestnetOracle.sol/IChainlinkOracle";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "decimal",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IChainlinkOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkOracleInterface {
    return new Interface(_abi) as IChainlinkOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IChainlinkOracle {
    return new Contract(address, _abi, runner) as unknown as IChainlinkOracle;
  }
}
