/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRelayerRegistryProxy__factory } from "./IRelayerRegistryProxy__factory";
export { RelayerRegistryBurnableProposal__factory } from "./RelayerRegistryBurnableProposal__factory";
