/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IENSResolver,
  IENSResolverInterface,
} from "../../../../../contracts/Governance/Aggregator/RelayerAggregator.sol/IENSResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "addr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "key",
        type: "string",
      },
    ],
    name: "text",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IENSResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IENSResolverInterface {
    return new Interface(_abi) as IENSResolverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IENSResolver {
    return new Contract(address, _abi, runner) as unknown as IENSResolver;
  }
}
