/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ENS,
  ENSInterface,
} from "../../../../../contracts/Governance/TORN/ENS.sol/ENS";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "resolver",
    outputs: [
      {
        internalType: "contract Resolver",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ENS__factory {
  static readonly abi = _abi;
  static createInterface(): ENSInterface {
    return new Interface(_abi) as ENSInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ENS {
    return new Contract(address, _abi, runner) as unknown as ENS;
  }
}
