/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Resolver,
  ResolverInterface,
} from "../../../../../contracts/Governance/TORN/ENS.sol/Resolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "addr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Resolver__factory {
  static readonly abi = _abi;
  static createInterface(): ResolverInterface {
    return new Interface(_abi) as ResolverInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Resolver {
    return new Contract(address, _abi, runner) as unknown as Resolver;
  }
}
