/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProxy__factory } from "./IProxy__factory";
export { NewImplementation__factory } from "./NewImplementation__factory";
export { ProposalUpgrade__factory } from "./ProposalUpgrade__factory";
