/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITornadoInstance__factory } from "./ITornadoInstance__factory";
export { TornadoProxyLight__factory } from "./TornadoProxyLight__factory";
