/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registry from "./registry";
export type { registry };
import type * as resolvers from "./resolvers";
export type { resolvers };
import type * as utils from "./utils";
export type { utils };
