/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGovernance } from "./IGovernance";
export type { ProposalStateChangeGovernance } from "./ProposalStateChangeGovernance";
