/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITornadoRouter__factory } from "./ITornadoRouter__factory";
export { InstanceRegistry__factory } from "./InstanceRegistry__factory";
