/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { GovernanceStakingUpgrade__factory } from "./GovernanceStakingUpgrade__factory";
