/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INameWrapper,
  INameWrapperInterface,
} from "../../../../contracts/Unaudited/TovarishRegistry.sol/INameWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INameWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): INameWrapperInterface {
    return new Interface(_abi) as INameWrapperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INameWrapper {
    return new Contract(address, _abi, runner) as unknown as INameWrapper;
  }
}
