/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IENSRegistry2__factory } from "./IENSRegistry2__factory";
export { IENSResolver2__factory } from "./IENSResolver2__factory";
export { INameWrapper__factory } from "./INameWrapper__factory";
export { IRelayerRegistry2__factory } from "./IRelayerRegistry2__factory";
export { ITovarishRegistry__factory } from "./ITovarishRegistry__factory";
export { TovarishRegistry__factory } from "./TovarishRegistry__factory";
