/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGasCompensationVault,
  IGasCompensationVaultInterface,
} from "../../../../../contracts/Governance/v2-vault-and-gas/GasCompensator.sol/IGasCompensationVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gasAmount",
        type: "uint256",
      },
    ],
    name: "compensateGas",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawToGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGasCompensationVault__factory {
  static readonly abi = _abi;
  static createInterface(): IGasCompensationVaultInterface {
    return new Interface(_abi) as IGasCompensationVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGasCompensationVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGasCompensationVault;
  }
}
