/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GasCompensator__factory } from "./GasCompensator__factory";
export { IGasCompensationVault__factory } from "./IGasCompensationVault__factory";
