/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AirdropMock } from "./AirdropMock";
export type { ENSMock } from "./ENSMock";
export type { TORNMock } from "./TORNMock";
export type { Timestamp } from "./Timestamp";
export type { VestingMock } from "./VestingMock";
export type { VoucherMock } from "./VoucherMock";
