/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IChainlinkOracle } from "./IChainlinkOracle";
export type { IOffchainOracle } from "./IOffchainOracle";
export type { TestnetOracle } from "./TestnetOracle";
