/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dummySol from "./Dummy.sol";
export * as proposalStateChangeGovernanceSol from "./ProposalStateChangeGovernance.sol";
export * as proposalUpgradeSol from "./ProposalUpgrade.sol";
export { MockGovernance__factory } from "./MockGovernance__factory";
export { Proposal__factory } from "./Proposal__factory";
