/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICore,
  ICoreInterface,
} from "../../../../../contracts/Governance/Aggregator/BalanceAggregator.sol/ICore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "lockedBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICore__factory {
  static readonly abi = _abi;
  static createInterface(): ICoreInterface {
    return new Interface(_abi) as ICoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICore {
    return new Contract(address, _abi, runner) as unknown as ICore;
  }
}
