/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICore__factory } from "./ICore__factory";
export { StakedView__factory } from "./StakedView__factory";
