/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Aggregator } from "./Aggregator";
export type { GovernanceAggregator } from "./GovernanceAggregator";
export type { RelayerAggregator } from "./RelayerAggregator";
