/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INameWrapper } from "./INameWrapper";
export type { TovarishRegistry } from "./TovarishRegistry";
